name: Docker Build & Push

on:
  workflow_dispatch: # Enkel handmatig triggeren

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v6-beta

      # 2️⃣ Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3️⃣ Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/calculator:${{ github.ref_name }}
          load: true
      # 5️⃣ Scan image for CVEs
      - name: Scan Docker image for CVEs
        uses: docker/scout-action@v1
        with:
          command: "scan"
          image: ${{ secrets.DOCKERHUB_USERNAME }}/calculator:latest
